-- 0002_init_content (up)
--
-- The content model. Every publishable thing on the site is a row in
-- content_item, which owns the fields that must behave identically for all of
-- them: slug, title, language, visibility, indexing policy, timestamps.
-- Kind-specific fields live in a detail table keyed 1:1 on content_item.id.
--
-- This shape exists so that cross-referencing, the public/private rule,
-- tagging, search and the relationship graph are implemented exactly once.
-- Adding a new kind later is a new detail table and new templates, never a
-- rewrite of those mechanisms.

CREATE TABLE IF NOT EXISTS content_item (
  id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  kind            ENUM('source', 'artifact', 'essay', 'person',
                       'organization', 'place', 'event') NOT NULL,
  -- URL segment, unique within a kind. Kinds occupy separate URL prefixes
  -- (/sources/, /artifacts/, ...) so a person and an essay may share a slug.
  slug            VARCHAR(190)    NOT NULL,
  title           VARCHAR(500)    NOT NULL,
  -- Title in the original language or script, when the main title is a
  -- translation or transliteration.
  title_original  VARCHAR(500)    NULL,
  -- BCP-47 language tag of the content itself ('ro', 'en', 'de', 'ro-Latn').
  -- The interface is English regardless; this describes the material.
  language        VARCHAR(20)     NULL,
  summary         TEXT            NULL,
  -- Nothing is public by accident. New rows are private and stay private
  -- until the operator deliberately publishes them.
  visibility      ENUM('private', 'public') NOT NULL DEFAULT 'private',
  -- Per-item override: keep a page publicly reachable but out of search
  -- indexes. Only consulted when site-wide indexing is enabled at all.
  noindex         TINYINT(1)      NOT NULL DEFAULT 0,
  published_at    DATETIME(3)     NULL,
  created_at      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
                                  ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_content_item_kind_slug (kind, slug),
  KEY ix_content_item_kind_visibility (kind, visibility, title),
  KEY ix_content_item_updated (updated_at)
  -- Search is a scan with LIKE against this accent-insensitive collation, so
  -- "Bucuresti" matches "Bucuresti" written with diacritics and vice versa,
  -- and a two-letter query behaves the same as a ten-letter one. A FULLTEXT
  -- index would be faster but imposes innodb_ft_min_token_size (3 by default),
  -- which silently drops short terms. At the scale of one researcher's corpus
  -- the scan is not measurable; revisit when the corpus makes it so.
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- --------------------------------------------------------------------------
-- Files
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS file_object (
  id                 BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  -- Content address. Uploading the same bytes twice reuses one stored file.
  sha256             CHAR(64)        NOT NULL,
  byte_size          BIGINT UNSIGNED NOT NULL,
  -- Determined by sniffing magic bytes on upload, never from the filename.
  mime_type          VARCHAR(190)    NOT NULL,
  original_filename  VARCHAR(255)    NOT NULL,
  -- Path relative to STORAGE_ROOT. Derived from the hash, never from
  -- user-supplied text, so a filename can never escape the storage root.
  storage_key        VARCHAR(255)    NOT NULL,
  created_at         DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_file_object_sha256 (sha256)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS file_derivative (
  id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  file_object_id  BIGINT UNSIGNED NOT NULL,
  -- 'thumb', 'web', 'pdf-page-1', ... Generated by the Python worker.
  variant         VARCHAR(32)     NOT NULL,
  mime_type       VARCHAR(190)    NOT NULL,
  width           INT UNSIGNED    NULL,
  height          INT UNSIGNED    NULL,
  byte_size       BIGINT UNSIGNED NOT NULL,
  storage_key     VARCHAR(255)    NOT NULL,
  created_at      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_file_derivative_object_variant (file_object_id, variant),
  CONSTRAINT fk_file_derivative_object
    FOREIGN KEY (file_object_id) REFERENCES file_object (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- --------------------------------------------------------------------------
-- Per-kind detail tables
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS source_detail (
  content_item_id  BIGINT UNSIGNED NOT NULL,
  -- CSL item type: book, chapter, article-journal, article-newspaper,
  -- manuscript, interview, thesis, webpage, ...
  csl_type         VARCHAR(50)     NOT NULL,
  -- The authoritative bibliographic record, in CSL-JSON. Citations are
  -- rendered from this and nothing else; every column below is a derived
  -- copy maintained by the application for listing, sorting and filtering.
  csl_json         JSON            NOT NULL,
  container_title  VARCHAR(500)    NULL,
  issued_year      SMALLINT        NULL,
  -- Archival provenance. Kept as real columns rather than inside csl_json
  -- because they are how the operator finds material again, and CSL has no
  -- adequate place for a call number.
  archive          VARCHAR(255)    NULL,
  archive_location VARCHAR(255)    NULL,
  call_number      VARCHAR(190)    NULL,
  url              VARCHAR(1000)   NULL,
  accessed_on      DATE            NULL,
  notes            TEXT            NULL,
  PRIMARY KEY (content_item_id),
  KEY ix_source_detail_year (issued_year),
  KEY ix_source_detail_type (csl_type),
  CONSTRAINT fk_source_detail_item
    FOREIGN KEY (content_item_id) REFERENCES content_item (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS artifact_detail (
  content_item_id    BIGINT UNSIGNED NOT NULL,
  file_object_id     BIGINT UNSIGNED NULL,
  provenance         TEXT            NULL,
  repository_name    VARCHAR(255)    NULL,
  physical_location  VARCHAR(255)    NULL,
  -- Free text: historical dating is often imprecise ("c. 1943", "n.d.").
  date_created       VARCHAR(100)    NULL,
  credit_line        VARCHAR(500)    NULL,
  rights_statement   VARCHAR(500)    NULL,
  PRIMARY KEY (content_item_id),
  KEY ix_artifact_detail_file (file_object_id),
  CONSTRAINT fk_artifact_detail_item
    FOREIGN KEY (content_item_id) REFERENCES content_item (id) ON DELETE CASCADE,
  -- Deleting the bytes must not silently delete the catalogue record.
  CONSTRAINT fk_artifact_detail_file
    FOREIGN KEY (file_object_id) REFERENCES file_object (id) ON DELETE SET NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS essay_detail (
  content_item_id  BIGINT UNSIGNED NOT NULL,
  -- Markdown is the source of truth. Together with the CSL-JSON in
  -- source_detail this is exactly what Pandoc needs to produce PDF, DOCX,
  -- HTML or LaTeX with correct Chicago notes.
  body_markdown    MEDIUMTEXT      NOT NULL,
  status           ENUM('draft', 'in_review', 'final') NOT NULL DEFAULT 'draft',
  word_count       INT UNSIGNED    NOT NULL DEFAULT 0,
  PRIMARY KEY (content_item_id),
  CONSTRAINT fk_essay_detail_item
    FOREIGN KEY (content_item_id) REFERENCES content_item (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- People and organizations share a table: both are agents that act in the
-- narrative and appear as nodes in the relationship graph. content_item.kind
-- distinguishes them.
CREATE TABLE IF NOT EXISTS agent_detail (
  content_item_id  BIGINT UNSIGNED NOT NULL,
  family_name      VARCHAR(190)    NULL,
  given_name       VARCHAR(190)    NULL,
  -- One per line: maiden names, pseudonyms, transliterations, Party names.
  alternate_names  TEXT            NULL,
  -- Free text for the same reason as artifact_detail.date_created.
  birth_date       VARCHAR(50)     NULL,
  death_date       VARCHAR(50)     NULL,
  founded_date     VARCHAR(50)     NULL,
  dissolved_date   VARCHAR(50)     NULL,
  occupation       VARCHAR(255)    NULL,
  biography        TEXT            NULL,
  PRIMARY KEY (content_item_id),
  KEY ix_agent_detail_family_name (family_name, given_name),
  CONSTRAINT fk_agent_detail_item
    FOREIGN KEY (content_item_id) REFERENCES content_item (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS place_detail (
  content_item_id   BIGINT UNSIGNED NOT NULL,
  -- WGS84. Six decimal places is roughly 0.1 m, well beyond what historical
  -- geography needs, and DECIMAL avoids float comparison surprises.
  latitude          DECIMAL(9, 6)   NULL,
  longitude         DECIMAL(9, 6)   NULL,
  geocode_precision ENUM('exact', 'approximate', 'region', 'unknown')
                                    NOT NULL DEFAULT 'unknown',
  geocoded_at       DATETIME(3)     NULL,
  country_code      CHAR(2)         NULL,
  admin_area        VARCHAR(190)    NULL,
  -- Place names change with borders and regimes; one per line.
  historical_names  TEXT            NULL,
  PRIMARY KEY (content_item_id),
  KEY ix_place_detail_coords (latitude, longitude),
  CONSTRAINT fk_place_detail_item
    FOREIGN KEY (content_item_id) REFERENCES content_item (id) ON DELETE CASCADE,
  -- Either both coordinates are present or neither; a lone latitude is a bug.
  CONSTRAINT ck_place_detail_coords
    CHECK ((latitude IS NULL) = (longitude IS NULL)),
  CONSTRAINT ck_place_detail_latitude
    CHECK (latitude IS NULL OR (latitude BETWEEN -90 AND 90)),
  CONSTRAINT ck_place_detail_longitude
    CHECK (longitude IS NULL OR (longitude BETWEEN -180 AND 180))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS event_detail (
  content_item_id  BIGINT UNSIGNED NOT NULL,
  start_date       DATE            NULL,
  end_date         DATE            NULL,
  -- How much of start_date/end_date is actually known. A date stored as
  -- 1944-01-01 with precision 'year' means "1944", not "1 January 1944".
  date_precision   ENUM('day', 'month', 'year', 'decade', 'unknown')
                                   NOT NULL DEFAULT 'unknown',
  place_item_id    BIGINT UNSIGNED NULL,
  PRIMARY KEY (content_item_id),
  KEY ix_event_detail_start (start_date),
  KEY ix_event_detail_place (place_item_id),
  CONSTRAINT fk_event_detail_item
    FOREIGN KEY (content_item_id) REFERENCES content_item (id) ON DELETE CASCADE,
  CONSTRAINT fk_event_detail_place
    FOREIGN KEY (place_item_id) REFERENCES content_item (id) ON DELETE SET NULL,
  CONSTRAINT ck_event_detail_dates
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- --------------------------------------------------------------------------
-- Cross-cutting: relationships, citations, tags
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS relationship_predicate (
  id             SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  code           VARCHAR(64)       NOT NULL,
  label          VARCHAR(190)      NOT NULL,
  -- How the edge reads from the other end, for the inverse listing.
  inverse_label  VARCHAR(190)      NOT NULL,
  is_symmetric   TINYINT(1)        NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_relationship_predicate_code (code)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS relationship (
  id            BIGINT UNSIGNED   NOT NULL AUTO_INCREMENT,
  from_item_id  BIGINT UNSIGNED   NOT NULL,
  to_item_id    BIGINT UNSIGNED   NOT NULL,
  predicate_id  SMALLINT UNSIGNED NOT NULL,
  note          VARCHAR(500)      NULL,
  -- An edge has its own visibility. A public edge between two public nodes
  -- is shown; anything else is admin-only. The relationship between two
  -- people can be more sensitive than either person's page.
  visibility    ENUM('private', 'public') NOT NULL DEFAULT 'private',
  created_at    DATETIME(3)       NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at    DATETIME(3)       NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
                                  ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_relationship_edge (from_item_id, predicate_id, to_item_id),
  KEY ix_relationship_to (to_item_id),
  KEY ix_relationship_predicate (predicate_id),
  CONSTRAINT fk_relationship_from
    FOREIGN KEY (from_item_id) REFERENCES content_item (id) ON DELETE CASCADE,
  CONSTRAINT fk_relationship_to
    FOREIGN KEY (to_item_id) REFERENCES content_item (id) ON DELETE CASCADE,
  CONSTRAINT fk_relationship_predicate
    FOREIGN KEY (predicate_id) REFERENCES relationship_predicate (id),
  CONSTRAINT ck_relationship_not_self CHECK (from_item_id <> to_item_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS citation (
  id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  -- Any content item may cite a source: an essay, but also an artifact's
  -- catalogue entry or a person's biographical note.
  citing_item_id  BIGINT UNSIGNED NOT NULL,
  source_item_id  BIGINT UNSIGNED NOT NULL,
  -- CSL locator, e.g. label 'page' with locator '45-47', or 'folio'/'12v'.
  label           VARCHAR(32)     NULL,
  locator         VARCHAR(190)    NULL,
  prefix          VARCHAR(255)    NULL,
  suffix          VARCHAR(255)    NULL,
  sort_order      INT UNSIGNED    NOT NULL DEFAULT 0,
  created_at      DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY ix_citation_citing (citing_item_id, sort_order),
  KEY ix_citation_source (source_item_id),
  CONSTRAINT fk_citation_citing
    FOREIGN KEY (citing_item_id) REFERENCES content_item (id) ON DELETE CASCADE,
  -- RESTRICT, not CASCADE: deleting a source that something still cites
  -- would silently break the scholarly apparatus. The operator must remove
  -- the citation first, which is a deliberate act.
  CONSTRAINT fk_citation_source
    FOREIGN KEY (source_item_id) REFERENCES content_item (id) ON DELETE RESTRICT
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS tag (
  id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug        VARCHAR(190)    NOT NULL,
  label       VARCHAR(190)    NOT NULL,
  created_at  DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_tag_slug (slug)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS content_tag (
  content_item_id  BIGINT UNSIGNED NOT NULL,
  tag_id           BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (content_item_id, tag_id),
  KEY ix_content_tag_tag (tag_id),
  CONSTRAINT fk_content_tag_item
    FOREIGN KEY (content_item_id) REFERENCES content_item (id) ON DELETE CASCADE,
  CONSTRAINT fk_content_tag_tag
    FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- Starter vocabulary. INSERT IGNORE keeps the migration re-runnable and lets
-- the operator delete predicates they do not want without them reappearing
-- with a different id.
INSERT IGNORE INTO relationship_predicate (code, label, inverse_label, is_symmetric) VALUES
  ('associated_with', 'Associated with',   'Associated with',   1),
  ('member_of',       'Member of',         'Has member',        0),
  ('employed_by',     'Employed by',       'Employer of',       0),
  ('family_of',       'Family of',         'Family of',         1),
  ('born_in',         'Born in',           'Birthplace of',     0),
  ('died_in',         'Died in',           'Place of death of', 0),
  ('located_in',      'Located in',        'Contains',          0),
  ('participated_in', 'Participated in',   'Had participant',   0),
  ('created_by',      'Created by',        'Creator of',        0),
  ('held_at',         'Held at',           'Holds',             0),
  ('depicts',         'Depicts',           'Depicted in',       0),
  ('mentions',        'Mentions',          'Mentioned in',      0),
  ('succeeded_by',    'Succeeded by',      'Preceded by',       0);
