/**
 * Public routes.
 *
 * These are served to anonymous visitors on the internet. Every read passes
 * `request.viewer` into the repository, so an administrator browsing the
 * public side sees their private items too -- with a marker in the template --
 * while everyone else sees only what has been published.
 */
import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { AppContext } from '../http/server.js';
import { renderPage } from '../http/context.js';
import { notFound } from '../http/errors.js';
import { findSourceBySlug, listCitingItems, listSources } from '../content/sources.js';
import { renderBibliographyEntry, renderNote } from '../citations/render.js';
import { creatorSummary, sourceTypeLabel } from '../citations/csl.js';

function slugParam(request: FastifyRequest): string {
  const slug = (request.params as { slug?: string }).slug ?? '';
  // Slugs are generated by `slugify`, so anything outside that alphabet
  // cannot correspond to a real row and is refused before it reaches SQL.
  if (!/^[a-z0-9-]{1,190}$/.test(slug)) throw notFound(`invalid slug "${slug}"`);
  return slug;
}

export function registerPublicRoutes(app: FastifyInstance, context: AppContext): void {
  const { config, pool } = context;

  app.get('/', async (request, reply) => {
    const recent = await listSources(pool, request.viewer, { limit: 10 });
    return renderPage(config, request, reply, 'home', {
      recentSources: recent.items,
      totalSources: recent.total,
    });
  });

  app.get('/sources', async (request, reply) => {
    const query = request.query as { q?: string; page?: string };
    const pageNumber = Math.max(Number(query.page ?? '1') || 1, 1);
    const perPage = 50;

    const result = await listSources(pool, request.viewer, {
      search: query.q,
      limit: perPage,
      offset: (pageNumber - 1) * perPage,
    });

    return renderPage(config, request, reply, 'sources/index', {
      sources: result.items.map((source) => ({
        ...source,
        typeLabel: sourceTypeLabel(source.cslType),
        creators: creatorSummary(source.csl.author ?? source.csl.editor),
        entry: renderBibliographyEntry(source.csl),
      })),
      total: result.total,
      page: pageNumber,
      pageCount: Math.max(Math.ceil(result.total / perPage), 1),
      search: query.q ?? '',
    });
  });

  app.get('/sources/:slug', async (request, reply) => {
    const slug = slugParam(request);
    const source = await findSourceBySlug(pool, slug, request.viewer);

    // Not found and not permitted are the same response on purpose; see
    // src/http/errors.ts.
    if (source === null) throw notFound(`source ${slug}`);

    const citedBy = await listCitingItems(pool, source.id, request.viewer);

    return renderPage(
      config,
      request,
      reply,
      'sources/show',
      {
        source,
        typeLabel: sourceTypeLabel(source.cslType),
        bibliographyEntry: renderBibliographyEntry(source.csl),
        note: renderNote(source.csl),
        citedBy,
        canonicalUrl: `${config.PUBLIC_BASE_URL}/sources/${encodeURIComponent(source.slug)}`,
      },
      { noindex: source.noindex || source.visibility !== 'public' },
    );
  });
}
