/**
 * Markdown rendering for prose.
 *
 * Two properties matter here:
 *
 * 1. **No raw HTML, ever.** markdown-it is configured with `html: false`, so
 *    an essay body cannot introduce a tag of its own. Everything in the output
 *    is generated by this module or escaped by markdown-it. That is what makes
 *    it safe to render an essay body without a sanitiser afterwards.
 *
 * 2. **References are a real inline rule**, not string substitution. Because
 *    raw HTML is disabled, injecting `<a>` into the source text would simply
 *    be escaped; and substituting before parsing would corrupt references
 *    inside code spans. A markdown-it rule sees the document structure, so
 *    `` `[[person:x]]` `` in a code span stays literal, as it should.
 *
 * A reference to something the viewer may not see renders as plain text with
 * no href, title, slug or id -- invariant 2 in CLAUDE.md.
 */
import MarkdownIt from 'markdown-it';
import type { CslItem } from '../citations/csl.js';
import { renderBibliography, renderNote } from '../citations/render.js';
import { isReferenceKind, referenceHref, referenceKey, type ReferenceKind } from './references.js';
import type { Viewer } from './visibility.js';

/** Shown in place of anything the viewer is not permitted to know exists. */
export const WITHHELD_LABEL = 'Reference withheld';

export interface ReferenceTarget {
  id: number;
  kind: string;
  slug: string;
  title: string;
  visible: boolean;
  /** Present for sources, so citations can be rendered. */
  csl?: CslItem | undefined;
}

export interface RenderOptions {
  /** Resolved targets, keyed by `referenceKey`. */
  targets: Map<string, ReferenceTarget>;
  viewer: Viewer;
}

export interface RenderedFootnote {
  number: number;
  /** Chicago note HTML, already sanitised by the citation renderer. */
  html: string;
}

export interface RenderedProse {
  html: string;
  footnotes: RenderedFootnote[];
  /** Chicago bibliography entries for every source cited, in style order. */
  bibliography: string[];
}

interface ReferenceMeta {
  kind: ReferenceKind;
  slug: string;
  argument: string | undefined;
}

interface RenderEnvironment {
  targets: Map<string, ReferenceTarget>;
  /** Citations in first-appearance order, one entry per marker. */
  citations: { slug: string; locator: string | undefined; csl: CslItem | undefined }[];
}

/**
 * Inline rule recognising `[[kind:slug|argument]]`.
 *
 * Registered before `link` so `[[` is claimed before markdown-it tries to read
 * it as a bracket expression.
 */
function referencePlugin(md: MarkdownIt): void {
  const pattern = /^\[\[([a-z_]{1,20}):([a-z0-9-]{1,190})(?:\|([^\]\n]{0,500}))?\]\]/;

  md.inline.ruler.before('link', 'reference', (state, silent) => {
    const start = state.pos;
    if (state.src.charCodeAt(start) !== 0x5b) return false;
    if (state.src.charCodeAt(start + 1) !== 0x5b) return false;

    // Bounded slice: a reference cannot exceed this, and slicing the whole
    // remaining document on every `[` would be quadratic on a long essay.
    const match = pattern.exec(state.src.slice(start, start + 800));
    if (match === null) return false;

    const [raw, kind, slug, argument] = match;
    if (kind === undefined || slug === undefined || !isReferenceKind(kind)) return false;

    if (!silent) {
      const token = state.push('reference', '', 0);
      token.meta = { kind, slug, argument } satisfies ReferenceMeta;
      token.content = raw;
    }

    state.pos += raw.length;
    return true;
  });

  md.renderer.rules.reference = (tokens, index, _options, environment) => {
    const token = tokens[index];
    const meta = token?.meta as ReferenceMeta | undefined;
    if (meta === undefined) return '';

    const env = environment as RenderEnvironment;
    const target = env.targets.get(referenceKey(meta.kind, meta.slug));
    const escape = md.utils.escapeHtml;

    if (meta.kind === 'cite') {
      // A citation to a source the viewer may not see cannot render its
      // bibliographic data: the title alone would disclose it.
      if (target === undefined || !target.visible || target.csl === undefined) {
        return `<span class="reference-withheld">[${escape(WITHHELD_LABEL)}]</span>`;
      }

      env.citations.push({ slug: meta.slug, locator: meta.argument, csl: target.csl });
      const number = env.citations.length;
      return (
        `<sup class="footnote-ref">` +
        `<a href="#fn-${number}" id="fnref-${number}">${number}</a>` +
        `</sup>`
      );
    }

    // A mention. The display text is what the prose said, which is often not
    // the target's title ("the Marshal", "her brother").
    const label = meta.argument ?? target?.title ?? meta.slug.replace(/-/g, ' ');

    if (target === undefined) {
      // Points at nothing: the target was deleted or the slug is wrong. Show
      // the words, flag it for the operator, and never emit a dead link.
      return `<span class="reference-broken" title="Unresolved reference">${escape(label)}</span>`;
    }

    if (!target.visible) {
      // Exists, but not for this viewer. Plain text only: no href, no title,
      // no slug, no id.
      return escape(label);
    }

    return (
      `<a class="reference reference-${escape(target.kind)}" ` +
      `href="${escape(referenceHref(target.kind, target.slug))}">${escape(label)}</a>`
    );
  };
}

function createRenderer(): MarkdownIt {
  const md = new MarkdownIt({
    // The single most important setting in this file.
    html: false,
    linkify: false,
    typographer: true,
    breaks: false,
  });

  md.use(referencePlugin);

  // markdown-it validates link protocols by default; this narrows it further
  // to the three that make sense in scholarly prose.
  md.validateLink = (url) => /^(https?:|mailto:|\/)/i.test(url.trim());

  return md;
}

const renderer = createRenderer();

/** Renders essay prose to HTML, with references resolved for this viewer. */
export function renderProse(markdown: string, options: RenderOptions): RenderedProse {
  const env: RenderEnvironment = { targets: options.targets, citations: [] };
  const html = renderer.render(markdown, env);

  const footnotes = env.citations.map((citation, index) => ({
    number: index + 1,
    html:
      citation.csl === undefined
        ? WITHHELD_LABEL
        : renderNote(citation.csl, { locator: citation.locator, label: 'page' }),
  }));

  // One bibliography entry per distinct source, ordered by the style's rules.
  const distinct = new Map<string, CslItem>();
  for (const citation of env.citations) {
    if (citation.csl !== undefined && !distinct.has(citation.slug)) {
      distinct.set(citation.slug, citation.csl);
    }
  }

  return { html, footnotes, bibliography: renderBibliography([...distinct.values()]) };
}

/** Renders a short Markdown fragment (an abstract, a note) with no references. */
export function renderFragment(markdown: string): string {
  return renderer.render(markdown, {
    targets: new Map(),
    citations: [],
  } satisfies RenderEnvironment);
}

/**
 * Counts words for the essay's stored `word_count`.
 *
 * References count as their display text, since that is what a reader sees.
 */
export function countWords(markdown: string): number {
  const prose = markdown
    .replace(
      /\[\[[a-z_]+:[a-z0-9-]+(?:\|([^\]\n]*))?\]\]/g,
      (_raw, display?: string) => display ?? ' ',
    )
    .replace(/[#*_`>[\]()!-]/g, ' ');
  const words = prose.split(/\s+/).filter((word) => word !== '');
  return words.length;
}
