/**
 * Markdown rendering for prose.
 *
 * Two properties matter here:
 *
 * 1. **No raw HTML, ever.** markdown-it is configured with `html: false`, so
 *    an essay body cannot introduce a tag of its own. Everything in the output
 *    is generated by this module or escaped by markdown-it. That is what makes
 *    it safe to render an essay body without a sanitiser afterwards.
 *
 * 2. **References are a real inline rule**, not string substitution. Because
 *    raw HTML is disabled, injecting `<a>` into the source text would simply
 *    be escaped; and substituting before parsing would corrupt references
 *    inside code spans. A markdown-it rule sees the document structure, so
 *    `` `[[person:x]]` `` in a code span stays literal, as it should.
 *
 * A reference to something the viewer may not see renders as plain text with
 * no href, title, slug or id -- invariant 2 in CLAUDE.md.
 */
import MarkdownIt from 'markdown-it';
import type Token from 'markdown-it/lib/token.mjs';
import type { CslItem } from '../citations/csl.js';
import { renderBibliography, renderNote } from '../citations/render.js';
import { isReferenceKind, referenceHref, referenceKey, type ReferenceKind } from './references.js';
import {
  TIMELINE_BLOCK_INFO,
  parseTimelineDirective,
  timelineDirectiveKey,
  type TimelineDirective,
  type TimelineEntry,
} from './timeline.js';
import type { Viewer } from './visibility.js';

/** Shown in place of anything the viewer is not permitted to know exists. */
export const WITHHELD_LABEL = 'Reference withheld';

export interface ReferenceTarget {
  id: number;
  kind: string;
  slug: string;
  title: string;
  visible: boolean;
  /** Present for sources, so citations can be rendered. */
  csl?: CslItem | undefined;
}

export interface RenderOptions {
  /** Resolved targets, keyed by `referenceKey`. */
  targets: Map<string, ReferenceTarget>;
  viewer: Viewer;
  /**
   * Entries for each timeline block, keyed by `timelineDirectiveKey`.
   *
   * Optional: omitted, a timeline block renders as an empty chronology rather
   * than throwing, so a caller that has no reason to resolve them (a word
   * count, a test of the reference rule) is not obliged to.
   */
  timelines?: ReadonlyMap<string, readonly TimelineEntry[]> | undefined;
}

export interface RenderedFootnote {
  number: number;
  /** Chicago note HTML, already sanitised by the citation renderer. */
  html: string;
}

export interface RenderedProse {
  html: string;
  footnotes: RenderedFootnote[];
  /** Chicago bibliography entries for every source cited, in style order. */
  bibliography: string[];
}

interface ReferenceMeta {
  kind: ReferenceKind;
  slug: string;
  argument: string | undefined;
}

interface RenderEnvironment {
  targets: Map<string, ReferenceTarget>;
  /** Citations in first-appearance order, one entry per marker. */
  citations: { slug: string; locator: string | undefined; csl: CslItem | undefined }[];
  timelines: ReadonlyMap<string, readonly TimelineEntry[]>;
  /**
   * Whether to put an id on each top-level block.
   *
   * Off for `renderFragment`, because a page renders several fragments and two
   * of them carrying `id="p1"` would be invalid HTML and an ambiguous anchor.
   */
  blockAnchors: boolean;
}

function emptyEnvironment(): RenderEnvironment {
  return { targets: new Map(), citations: [], timelines: new Map(), blockAnchors: false };
}

/**
 * The top-level blocks of a parsed document, in document order.
 *
 * One walk, used twice: once by the renderer to emit `id="pN"`, and once by
 * `blockAnchorsFor` to tell `rebuildReferences` which N a reference fell in.
 * Two hand-kept copies of this numbering would eventually disagree, and a
 * backlink would then land on the wrong paragraph.
 *
 * A closing token and an inline token are skipped: the first has no source
 * map, the second is nested inside a block that already counted.
 */
function topLevelBlocks(tokens: readonly Token[]): { token: Token; ordinal: number }[] {
  const blocks: { token: Token; ordinal: number }[] = [];
  for (const token of tokens) {
    if (token.level !== 0 || token.nesting === -1 || token.map === null) continue;
    blocks.push({ token, ordinal: blocks.length + 1 });
  }
  return blocks;
}

function blockAnchorPlugin(md: MarkdownIt): void {
  md.core.ruler.push('block_anchors', (state) => {
    const env = state.env as RenderEnvironment;
    if (env.blockAnchors !== true) return;
    for (const { token, ordinal } of topLevelBlocks(state.tokens)) {
      token.attrSet('id', `p${ordinal}`);
    }
  });
}

/**
 * Inline rule recognising `[[kind:slug|argument]]`.
 *
 * Registered before `link` so `[[` is claimed before markdown-it tries to read
 * it as a bracket expression.
 */
function referencePlugin(md: MarkdownIt): void {
  const pattern = /^\[\[([a-z_]{1,20}):([a-z0-9-]{1,190})(?:\|([^\]\n]{0,500}))?\]\]/;

  md.inline.ruler.before('link', 'reference', (state, silent) => {
    const start = state.pos;
    if (state.src.charCodeAt(start) !== 0x5b) return false;
    if (state.src.charCodeAt(start + 1) !== 0x5b) return false;

    // Bounded slice: a reference cannot exceed this, and slicing the whole
    // remaining document on every `[` would be quadratic on a long essay.
    const match = pattern.exec(state.src.slice(start, start + 800));
    if (match === null) return false;

    const [raw, kind, slug, argument] = match;
    if (kind === undefined || slug === undefined || !isReferenceKind(kind)) return false;

    if (!silent) {
      const token = state.push('reference', '', 0);
      token.meta = { kind, slug, argument } satisfies ReferenceMeta;
      token.content = raw;
    }

    state.pos += raw.length;
    return true;
  });

  md.renderer.rules.reference = (tokens, index, _options, environment) => {
    const token = tokens[index];
    const meta = token?.meta as ReferenceMeta | undefined;
    if (meta === undefined) return '';

    const env = environment as RenderEnvironment;
    const target = env.targets.get(referenceKey(meta.kind, meta.slug));
    const escape = md.utils.escapeHtml;

    if (meta.kind === 'cite') {
      // A citation to a source the viewer may not see cannot render its
      // bibliographic data: the title alone would disclose it.
      if (target === undefined || !target.visible || target.csl === undefined) {
        return `<span class="reference-withheld">[${escape(WITHHELD_LABEL)}]</span>`;
      }

      env.citations.push({ slug: meta.slug, locator: meta.argument, csl: target.csl });
      const number = env.citations.length;
      return (
        `<sup class="footnote-ref">` +
        `<a href="#fn-${number}" id="fnref-${number}">${number}</a>` +
        `</sup>`
      );
    }

    // A mention. What the prose itself said, which is often not the target's
    // title ("the Marshal", "her brother"). It is the operator's own words and
    // is already on the page, so it is shown whatever the target turns out to
    // be -- including when the target is withheld.
    const written = meta.argument;

    if (target === undefined) {
      // Points at nothing: the target was deleted or the slug is wrong. There
      // is no record to protect, so the slug read as words is the operator's
      // own typing and the most useful thing to show. Flagged for them, and
      // never a dead link.
      const label = written ?? meta.slug.replace(/-/g, ' ');
      return `<span class="reference-broken" title="Unresolved reference">${escape(label)}</span>`;
    }

    if (!target.visible) {
      // Exists, but not for this viewer. Plain text only: no href, no title,
      // no slug, no id.
      //
      // `target.title` is deliberately NOT a fallback here. The prose named a
      // slug; the catalogue title is a different string that the operator
      // never wrote into the sentence, and it can say considerably more than
      // they did -- "Maria Doe (informant, dosar 2231)" where the prose said
      // only [[person:maria-doe]]. Falling back to the slug would be no better:
      // invariant 2 rules out the title and the slug alike.
      //
      // So without the operator's own words there is nothing left that is safe
      // to say, and the reader is told that plainly -- the same marker, and the
      // same markup, a withheld citation has used all along.
      if (written === undefined) {
        return `<span class="reference-withheld">[${escape(WITHHELD_LABEL)}]</span>`;
      }
      return escape(written);
    }

    const label = written ?? target.title;
    return (
      `<a class="reference reference-${escape(target.kind)}" ` +
      `href="${escape(referenceHref(target.kind, target.slug))}">${escape(label)}</a>`
    );
  };
}

/**
 * The ```timeline block.
 *
 * A fence rather than a new syntax, so the body stays readable in any other
 * Markdown editor and an author who has not resolved the entries still sees
 * what the block asked for. Discovery goes through markdown-it's tokenizer, not
 * a regex over the source: a fence nested in another fence, or sitting inside
 * an indented code block, is not a directive and must not be read as one.
 *
 * The entries were filtered by `resolveTimelineDirectives` for this viewer, so
 * a private event is simply not in the list -- no gap, no "withheld" marker.
 * An absence has to be indistinguishable from never having existed.
 */
function timelinePlugin(md: MarkdownIt): void {
  const fallback = md.renderer.rules.fence;

  md.renderer.rules.fence = (tokens, index, options, environment, self) => {
    const token = tokens[index];
    const info = token?.info.trim().toLowerCase();

    if (token === undefined || info !== TIMELINE_BLOCK_INFO) {
      return fallback === undefined
        ? self.renderToken(tokens, index, options)
        : fallback(tokens, index, options, environment, self);
    }

    const env = environment as RenderEnvironment;
    const directive = parseTimelineDirective(token.content);
    const entries = env.timelines.get(timelineDirectiveKey(directive)) ?? [];
    const escape = md.utils.escapeHtml;
    const id = token.attrGet('id');

    const heading =
      directive.title === null ? '' : `<h3 class="timeline-title">${escape(directive.title)}</h3>`;

    if (entries.length === 0) {
      return (
        `<div class="timeline"${id === null ? '' : ` id="${escape(id)}"`}>${heading}` +
        `<p class="empty">No events to show here.</p></div>`
      );
    }

    const items = entries
      .map((entry) => {
        const place =
          entry.place === null
            ? ''
            : ` <span class="timeline-place">${escape(entry.place.title)}</span>`;
        return (
          `<li><span class="timeline-date">${escape(entry.dateLabel)}</span> ` +
          `<a href="${escape(entry.href)}">${escape(entry.title)}</a>${place}</li>`
        );
      })
      .join('');

    return (
      `<div class="timeline"${id === null ? '' : ` id="${escape(id)}"`}>${heading}` +
      `<ol class="timeline-list">${items}</ol></div>`
    );
  };
}

function createRenderer(): MarkdownIt {
  const md = new MarkdownIt({
    // The single most important setting in this file.
    html: false,
    linkify: false,
    typographer: true,
    breaks: false,
  });

  md.use(referencePlugin);
  md.use(timelinePlugin);
  // Pushed last so it sees the final token stream.
  md.use(blockAnchorPlugin);

  // markdown-it validates link protocols by default; this narrows it further
  // to the three that make sense in scholarly prose.
  md.validateLink = (url) => /^(https?:|mailto:|\/)/i.test(url.trim());

  return md;
}

const renderer = createRenderer();

/** Renders essay prose to HTML, with references resolved for this viewer. */
export function renderProse(markdown: string, options: RenderOptions): RenderedProse {
  const env: RenderEnvironment = {
    targets: options.targets,
    citations: [],
    timelines: options.timelines ?? new Map(),
    blockAnchors: true,
  };
  const html = renderer.render(markdown, env);

  const footnotes = env.citations.map((citation, index) => ({
    number: index + 1,
    html:
      citation.csl === undefined
        ? WITHHELD_LABEL
        : renderNote(citation.csl, { locator: citation.locator, label: 'page' }),
  }));

  // One bibliography entry per distinct source, ordered by the style's rules.
  const distinct = new Map<string, CslItem>();
  for (const citation of env.citations) {
    if (citation.csl !== undefined && !distinct.has(citation.slug)) {
      distinct.set(citation.slug, citation.csl);
    }
  }

  return { html, footnotes, bibliography: renderBibliography([...distinct.values()]) };
}

/** Renders a short Markdown fragment (an abstract, a note) with no references. */
export function renderFragment(markdown: string): string {
  return renderer.render(markdown, emptyEnvironment());
}

/**
 * Every timeline block in a body, in document order.
 *
 * Uses the same parse as rendering, so what is resolved and what is drawn can
 * never be two different sets of blocks.
 */
export function parseTimelineDirectives(markdown: string): TimelineDirective[] {
  return locateTimelineBlocks(markdown).map((block) => block.directive);
}

export interface TimelineBlockLocation {
  directive: TimelineDirective;
  /** Source lines the fence occupies, as a half-open range. */
  startLine: number;
  endLine: number;
}

/**
 * Every timeline block with the lines it occupies.
 *
 * The compile path needs the position as well as the directive, because it
 * replaces the block with plain Markdown before Pandoc sees it. Line ranges
 * come from the tokenizer rather than from a search for ``` so a fence nested
 * inside another one is not mistaken for a block of its own.
 */
export function locateTimelineBlocks(markdown: string): TimelineBlockLocation[] {
  const blocks: TimelineBlockLocation[] = [];
  for (const token of renderer.parse(markdown, emptyEnvironment())) {
    if (token.type !== 'fence' || token.map === null) continue;
    if (token.info.trim().toLowerCase() !== TIMELINE_BLOCK_INFO) continue;
    blocks.push({
      directive: parseTimelineDirective(token.content),
      startLine: token.map[0],
      endLine: token.map[1],
    });
  }
  return blocks;
}

/** Offsets of the first character of each line, for the offset->line lookup. */
function lineStartOffsets(markdown: string): number[] {
  const starts = [0];
  for (let index = 0; index < markdown.length; index += 1) {
    if (markdown.charCodeAt(index) === 0x0a) starts.push(index + 1);
  }
  return starts;
}

function lineForOffset(lineStarts: readonly number[], offset: number): number {
  let low = 0;
  let high = lineStarts.length - 1;
  while (low < high) {
    const middle = Math.ceil((low + high) / 2);
    if ((lineStarts[middle] ?? 0) <= offset) low = middle;
    else high = middle - 1;
  }
  return low;
}

/**
 * Which top-level block each character offset falls in; 1-based, null if none.
 *
 * `parseReferences` reports character offsets while markdown-it reports line
 * ranges, so the two are bridged here rather than in the caller. The numbering
 * is the one `renderProse` emits as `id="pN"`, because both come from
 * `topLevelBlocks` -- which is what lets a stored anchor address a real
 * paragraph.
 */
export function blockAnchorsFor(markdown: string, offsets: readonly number[]): (number | null)[] {
  if (offsets.length === 0) return [];

  const blocks = topLevelBlocks(renderer.parse(markdown, emptyEnvironment()));
  const lineStarts = lineStartOffsets(markdown);

  return offsets.map((offset) => {
    const line = lineForOffset(lineStarts, offset);
    const found = blocks.find(
      ({ token }) => token.map !== null && line >= token.map[0] && line < token.map[1],
    );
    return found?.ordinal ?? null;
  });
}

/**
 * Counts words for the essay's stored `word_count`.
 *
 * References count as their display text, since that is what a reader sees.
 */
export function countWords(markdown: string): number {
  const prose = markdown
    .replace(
      /\[\[[a-z_]+:[a-z0-9-]+(?:\|([^\]\n]*))?\]\]/g,
      (_raw, display?: string) => display ?? ' ',
    )
    .replace(/[#*_`>[\]()!-]/g, ' ');
  const words = prose.split(/\s+/).filter((word) => word !== '');
  return words.length;
}
